#!/usr/bin/env bash
# Assemble the shared Markdown render kit into a directory, for embedding in a
# native client.
#
# Usage:  tools/dist-renderer.sh <outdir>
#
# The kit is a plain static site: render/index.html hosts the compiled render
# pipeline and exposes globalThis.MyNotesRender (see web/ts/render/host.ts).
# Load it in a web view, then push Markdown and the theme through that API.
#
# This is a copy, not a build: every file below is either a committed vendor
# bundle or tsc output produced by build.sh. Run build.sh first. No npm, no
# esbuild, no network — matching the project's supply-chain stance.
#
# The output mirrors web/static/'s directory layout, because render/index.html's
# import map and the compiled modules reference each other by relative path
# (../vendor/…, ../util/…). Flattening the tree would break them.
set -euo pipefail

if [ $# -ne 1 ]; then
  echo "usage: $(basename "$0") <outdir>" >&2
  exit 1
fi

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATIC="$REPO/web/static"
OUT="$1"

# Vendor bundles the render pipeline imports, by import-map specifier. Matched by
# version-stamped prefix (markdown-it-14.2.0.js, …) so a version bump needs no
# edit here — the same technique as web/ts/test-hooks.mjs. Deliberately excludes
# codemirror and preact: those belong to the web UI's editor, not the renderer.
VENDOR_PREFIXES=(markdown-it- dompurify- emoji- lucide- asciimath- mermaid-)

# Everything else, as paths relative to web/static/.
FILES=(
  render/index.html
  render/note.css
  render/host.js
  util/markdown.js
  util/mermaid.js
  basepath.js
)

# Resolve the single file matching a versioned vendor prefix, failing loudly if
# a rebuild left none or several behind.
vendor_file() {
  local prefix="$1" matches=()
  shopt -s nullglob
  matches=("$STATIC/vendor/$prefix"*.js)
  shopt -u nullglob
  if [ ${#matches[@]} -ne 1 ]; then
    echo "$(basename "$0"): expected exactly one $prefix*.js in $STATIC/vendor, found ${#matches[@]}" >&2
    exit 1
  fi
  printf '%s\n' "${matches[0]}"
}

for f in "${FILES[@]}"; do
  if [ ! -f "$STATIC/$f" ]; then
    echo "$(basename "$0"): missing $STATIC/$f — run ./build.sh first" >&2
    exit 1
  fi
done

# Replace the whole tree rather than merging, so a bundle that is no longer part
# of the kit (or an old version-stamped name) cannot linger in the consumer.
rm -rf "$OUT"
mkdir -p "$OUT/render" "$OUT/util" "$OUT/vendor"

for f in "${FILES[@]}"; do
  cp "$STATIC/$f" "$OUT/$f"
done

for prefix in "${VENDOR_PREFIXES[@]}"; do
  cp "$(vendor_file "$prefix")" "$OUT/vendor/"
done

# Record what was copied, so a consumer repo's diff shows the version bump.
{
  echo "MyNotes render kit"
  echo "Generated by tools/dist-renderer.sh — do not edit these files by hand;"
  echo "re-run the script against the mynotes repository instead."
  echo
  echo "Entry point: render/index.html (globalThis.MyNotesRender)"
  echo
  ( cd "$OUT" && find . -type f ! -name MANIFEST | sort | sed 's|^\./|  |' )
} > "$OUT/MANIFEST"

echo "Wrote the render kit to $OUT (entry point: render/index.html)"
